---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.component.service.http.gw }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: {{ .Values.component.service.http.protocol }}
      protocol: HTTP
    hosts:
    {{- range .Values.component.service.http.hostnames }}
    - {{ . }}
    {{- end}}

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.component.service.http.vs }}
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  {{- range .Values.component.service.http.hostnames }}
  - {{ . }}
  {{- end}}
  gateways:
  - {{ .Values.component.service.http.gw }}
  http:
  - route:
    - destination:
        host: {{ .Values.component.service.http.name }}.{{ .Values.namespace }}.svc.cluster.local
        port:
          number: 80
      weight: 100
