apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.component.efs.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: "efs"
  resources:
    requests:
      storage: "{{ .Values.component.efs.size }}"
