---
apiVersion: v1
kind: Secret
metadata:
  name: ejabberd-yml
  namespace: ejabberd
type: Opaque
stringData:
  ejabberd.yml: |-
{{ .Files.Get .Values.ejabberd_yml | indent 4 }}

---
apiVersion: v1
kind: Secret
metadata:
  name: erlang-cookie
  namespace: ejabberd
type: Opaque
stringData:
  .erlang.cookie: |-
{{ .Files.Get .Values.erlang_cookie | indent 4 }}
