---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component.service.http.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.component.name }}
  ports:
  - name: {{ .Values.component.service.http.protocol }}
    protocol: TCP
    port: 80
    targetPort: {{ .Values.component.service.http.port }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component.name }}-headless
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.component.name }}
  clusterIP: None
  clusterIPs:
  - None
  ports:
  - name: cluster
    protocol: TCP
    port: 4369
    targetPort: 4369
  publishNotReadyAddresses: true
  sessionAffinity: None
  type: ClusterIP
